const products = [
    {
      id: 1,
      name: "Apple AirPods Pro (2nd Gen)",
      description: "Active Noise Cancellation with Adaptive Transparency and Personalized Spatial Audio.",
      category: "Electronics",
      price: 249.99,
      image: "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg",
    },
    {
      id: 2,
      name: "Samsung Galaxy Watch 6",
      description: "Smart fitness tracking, heart rate monitoring, and AMOLED display.",
      category: "Wearables",
      price: 299.99,
      image: "https://m.media-amazon.com/images/I/71elbYR1eEL._AC_UY218_.jpg",
    },
    {
      id: 3,
      name: "Logitech MX Master 3S",
      description: "Ergonomic wireless mouse with ultra-fast scrolling and customizable buttons.",
      category: "Accessories",
      price: 99.99,
      image: "https://m.media-amazon.com/images/I/51cXd5gEhIL._AC_UY218_.jpg",
    },
    {
      id: 4,
      name: "Sony WH-1000XM5 Headphones",
      description: "Industry-leading noise cancellation with superior sound quality.",
      category: "Audio",
      price: 399.99,
      image: "https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_SL1500_.jpg",
    },
    {
      id: 5,
      name: "Kindle Paperwhite (11th Gen)",
      description: "Waterproof e-reader with adjustable warm light and high-resolution display.",
      category: "Books",
      price: 139.99,
      image: "https://m.media-amazon.com/images/I/61jovjd+f9L._AC_SL1500_.jpg",
    },
    {
      id: 6,
      name: "Anker PowerCore 20,000mAh",
      description: "High-speed portable charger with PowerIQ and USB-C compatibility.",
      category: "Charging",
      price: 49.99,
      image: "https://m.media-amazon.com/images/I/71PvtLA1XjL._AC_UY218_.jpg",
    },
    {
      id: 7,
      name: "Canon EOS R50 Mirrorless Camera",
      description: "Compact 24.2MP mirrorless camera with 4K video recording.",
      category: "Cameras",
      price: 879.99,
      image: "https://m.media-amazon.com/images/I/916GGqnsG+L._AC_UY218_.jpg",
    },
    {
      id: 8,
      name: "Amazon Fire TV Stick 4K",
      description: "Streaming device with Alexa Voice Remote and Dolby Vision support.",
      category: "Streaming",
      price: 49.99,
      image: "https://m.media-amazon.com/images/I/71RMJHjJa0L._AC_UY218_.jpg",
    },
    {
      id: 9,
      name: "Razer BlackWidow V4 Pro",
      description: "RGB mechanical gaming keyboard with programmable macros.",
      category: "Gaming",
      price: 199.99,
      image: "https://m.media-amazon.com/images/I/81JG5E6nJXL._AC_UY218_.jpg",
    },
    {
      id: 10,
      name: "Samsung 49-inch Curved Gaming Monitor",
      description: "Ultra-wide 49-inch monitor with 240Hz refresh rate and QHD resolution.",
      category: "Monitors",
      price: 1399.99,
      image: "https://m.media-amazon.com/images/I/81Iv5fQAyBL._AC_UY218_.jpg",
    },
  ];
  
  export default products;  